name: syndiff
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.24.2
  - pandas=1.5.3
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-cuda=12.4
  - pytorch-lightning=1.9.4
  - tensorboard=2.12.0
  - scikit-learn=1.2.1
  - matplotlib=3.7.1
  - notebook=6.5.3
  - pip:
      - torchmetrics==0.11.4
